[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[dependencies]
clearscreen = "2.0.0"
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
uuid = {version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics"]}